#!/usr/bin/python

'''
soup2breve - Robert Leftwich

Requires BeautifulSoup - http://www.crummy.com/software/BeautifulSoup/
'''

import sys
from breve.tools.soup2breve import convert_file, usage

if len ( sys.argv ) < 2:
    usage ( )
    raise SystemExit

result = soup2breve.convert_file ( sys.argv [ 1 ], dict ( meta=meta_handler ) )
print ''.join ( result )
